### ISSUE TITLE
export to image is partial

### ISSUE THREAD

**Issue by Madko** [csgib/BRAINMAP#1]
When I do an export, the image covers only about 90% of my schema. It seems the furthest object on the right is cutted on its center, wherever it is located.

**Comment by csgib** [comment]
Thanks for the report.... I found the bug , and fix it .... hope a commit in the day

**Comment by csgib** [comment]
Fix with last commit. You should reload the archive and recreate the bdd cause others commit make change on database. Sorry for that.... in the futur i will try to provide smooth upgrades
